name: app-stacks

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  app-build:
    name: app build
    runs-on: ubuntu-latest
    environment: st-app
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          echo "Build app"
  app-deploy:
    name: app deploy
    needs: app-build
    runs-on: ubuntu-latest
    environment: st-app
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: |
          echo "Deploy app"
  app-system-test:
    name: app system test
    needs:
      - app-build
      - app-deploy
    runs-on: ubuntu-latest
    environment: st-app-system-test
    steps:
      - uses: actions/checkout@v4
      - name: system test
        run: |
          echo "System test app failed"
          exit 1
  slack:
    name: slack notification
    environment: st-app
    needs:
      - app-build
      - app-deploy
      - app-system-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: slack notification
        run: |
          echo "Slack notification"
